version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: aforro
      POSTGRES_USER: aforro
      POSTGRES_PASSWORD: aforro
  redis:
    image: redis
  celery:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db
